DROP DATABASE IF EXISTS project_calendar;

CREATE DATABASE IF NOT EXISTS project_calendar;
USE project_calendar;

CREATE TABLE IF NOT EXISTS User (
    uID INT AUTO_INCREMENT PRIMARY KEY,
    fName VARCHAR(100) NOT NULL,
    lName VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    is_admin BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS Task (
    tID INT AUTO_INCREMENT PRIMARY KEY,
    description TEXT NOT NULL,
    date DATE NOT NULL,
    uID INT NOT NULL,
    FOREIGN KEY (uID) REFERENCES User(uID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS List (
    lID INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    uID INT NOT NULL,
    FOREIGN KEY (uID) REFERENCES User(uID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ListElement (
    leID INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    is_checked BOOLEAN NOT NULL DEFAULT FALSE,
    lID INT NOT NULL,
    FOREIGN KEY (lID) REFERENCES List(lID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS UserSharesTask (
    sharer_uID INT NOT NULL,
    shared_with_uID INT NOT NULL,
    is_accepted BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (sharer_uID, shared_with_uID),
    FOREIGN KEY (sharer_uID) REFERENCES User(uID) ON DELETE CASCADE,
    FOREIGN KEY (shared_with_uID) REFERENCES User(uID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS UserSharesList (
    sharer_uID INT NOT NULL,
    shared_with_uID INT NOT NULL,
    is_accepted BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (sharer_uID, shared_with_uID),
    FOREIGN KEY (sharer_uID) REFERENCES User(uID) ON DELETE CASCADE,
    FOREIGN KEY (shared_with_uID) REFERENCES User(uID) ON DELETE CASCADE
);